### ISSUE TITLE
Docs for compile-lm : error too many arguments

### ISSUE THREAD

**Issue by colbec** [irstlm-team/irstlm#2]
Using IRSTLM on Linux openSUSE Leap 42.1 - 
when using compile-lm with option text, for example, the option must be specified as 
`compile-lm --text=yes input output`
Note the "=" in the text option. If this is omitted on openSUSE then result is:
> DEBUG_LEVEL:0/1 Warning: Too many arguments

In the pdf docs the "=" is omitted in the example.
This may be OS specific, I don't know, but it is certainly confusing. May I suggest a extra note at this point?

**Comment by nicolabertoldi** [comment]
the current version of IRSTLM requires the '='
I will emend the pdf manual accordingly

thanks 
Nicola
