### ISSUE TITLE
Should qplsa.sh script be distributed, given its current status?

### ISSUE THREAD

**Issue by giuliopaci** [irstlm-team/irstlm#5]
I just had a look at the command line help of every installed scripts and binaries and, by trying

```LC_ALL=C /usr/lib/irstlm/bin/qplsa.sh -h```

I obtained

```
rm: cannot remove '/panfs/panfem/test-hlt/federico/plsa/CC/tlist': No such file or directory
/usr/lib/irstlm/bin/qplsa.sh: line 39: qsub: command not found
```

In the source I cannot find any usage/purpose instruction. I think this script should either not be distributed/installed or, probably better, improved and generalized.

**Comment by nicolabertoldi** [comment]
removed qplsa.sh from the repo
because too much related to SGE

**Comment by senarvi** [comment]
When trying to build the project, I get this error:
No rule to make target `qplsa.sh', needed by `all-am'.

**Comment by nicolabertoldi** [comment]
removed qplsa.h from the compilation scripts based on AutoMake toolkit
