### ISSUE TITLE
Upper case <S> tag causes problems

### ISSUE THREAD

**Issue by qbolec** [irstlm-team/irstlm#6]
When running a command like this:
```
$ ~/kaldi-trunk/tools/irstlm/bin/build-sublm.pl --verbose --witten-bell --size 2 --ngrams "/bin/gunzip -c ngram.dict.000.gz" -sublm lm.dict.000
$ ~/kaldi-trunk/tools/irstlm/bin/merge-sublm.pl --size 2 --sublm lm.dict -lm lm.ilm.gz
$ ~/kaldi-trunk/tools/irstlm/bin/compile-lm lm.ilm.gz -t=yes /dev/stdout | grep -v unk | gzip -c > arpa.gz
```
I got a
```
warning: missing back-off (at level 1) for ngram <S> dekapitalizacja    0 (and possibly for others)
```
The `<S> dekapitalizacja` bigram is the first bigram which starts with `<S>` in my ngram.dict.000.gz file which I've created manually.

I susspect that the issue is caused by a missing /i switch in this line:
https://github.com/irstlm-team/irstlm/blob/master/scripts/merge-sublm.pl#L84
although, frankly I have no idea what is the purpose of this line.

**Comment by nicolabertoldi** [comment]
<s> and </s> are reserved tokens of IRSTLM to identify the beginning and the end of a sentence; they are lowercased.
The corresponding uppercased tokens (<S> and </S>) are common tokens.

Hence, in your case, "<S> dekapitalizacja" refers to a standard bigram, and not to a unigram ("dekapitalizacja") at the beginning of a sentence.

The warning you got, refers to the fact that the set of your ngrams is not complete, in the sense that the unigram "<S>" is not included in your data.
In fact, IRSTLM assumes that the ngrams are collected from a real text; hence if the bigram "word_a word_b" is present also "word_a" has to be present.

Your warning can arise when the ngrams are not generated using the IRSTLM tool, but rather using an external "independent" way, like in your case.

Nevertheless, it is just a warning, and it does not impact significantly your model.

I close the issue, but please feel free to reopen here for any further doubt or related problem.

**Comment by qbolec** [comment]
Perhaps you are right, but the thing that does seem odd is that in the file https://github.com/irstlm-team/irstlm/blob/master/scripts/merge-sublm.pl the `<s>` and `<S>` are mentioned several times in an inconsistent (in my opinion) way:

- In line https://github.com/irstlm-team/irstlm/blob/master/scripts/merge-sublm.pl#L84 it is used in a case-sensitive regexp `~/<s>/`
- In line https://github.com/irstlm-team/irstlm/blob/master/scripts/merge-sublm.pl#L146 it is used in a find-replace `~s/<S>/<s>/g;`
- In line https://github.com/irstlm-team/irstlm/blob/master/scripts/merge-sublm.pl#L156 it is used in a case-insensitive regexp `~/<s>/i`

In particular the last two lines seem to indicate some partial support for uppercased `<S>` while the first one does not.
